version: '3.9'
services:
  postgres:
    # 今回はpostgresをサービスとして定義
    image: postgres:12-alpine
    # コンテナの名前を指定
    container_name: postgres
    # 環境変数を設定
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=r128811
      - POSTGRES_DB=mydb
    # データの永続化
    volumes:
      # postgresディレクトリを/var/lib/postgresql/dataにマウントする
      - .data:/var/lib/postgresql/data
    # ポートの指定
    ports:
      - 5432:5432
volumes:
  posgtres: